import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, rm, readdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { getModel } from "@mariozechner/pi-ai";
import { createRuntimeLog } from "../src/runtime/runtime-log.js";
import { conversationLog } from "../src/runtime/conversation-log.js";
import { assistantText } from "../src/agent/model-message.js";
import { replayEvents } from "../src/context/projection.js";
import { createReplayCache } from "../src/context/replay-cache.js";

test("incremental replay equals full replay, survives restart and invalidates reset, forgetting and corruption", async (t) => {
  const dir = await mkdtemp(join(tmpdir(), "replay-cache-")); t.after(() => rm(dir, { recursive: true, force: true }));
  const log = conversationLog(createRuntimeLog(dir), "c");
  const model = getModel("openai", "gpt-4o-mini");
  for (let i = 0; i < 30; i++) {
    await log.append({ type: "message", role: "user", requestId: `r${i}`, text: `question${i}` });
    await log.append({ type: "answer_generated", requestId: `r${i}`, text: `answer${i}` });
    await log.append({ type: "run_succeeded", runId: `r${i}`, requestId: `r${i}`, result: { kind: "model" } });
  }
  const result = { content: [{ type: "text" as const, text: "checked file" }], details: {}, isError: false };
  const archive = await log.archive(result);
  const message = assistantText("", model); message.content = [{ type: "toolCall", id: "old-call", name: "read", arguments: { path: "file" } }];
  await log.append({ type: "model_message", requestId: "r29", message });
  await log.append({ type: "tool_dispatch", requestId: "r29", toolCallId: "old-call", toolName: "read", args: { path: "file" } });
  await log.append({ type: "tool_result", requestId: "r29", toolCallId: "old-call", toolName: "read", result, archive });
  await log.append({ type: "message", role: "user", requestId: "current", text: "now" });
  let recoveries = 0;
  const countedLog = { ...log, recoverArchive: async (...args: Parameters<typeof log.recoverArchive>) => { recoveries++; return log.recoverArchive(...args); } };
  let cache = createReplayCache(dir, "c/model/prompt");
  const compare = async (id: string) => {
    const actual = await cache.replay(countedLog, id, model, false);
    const expected = await replayEvents(log, id, model, false);
    assert.deepEqual({ ...actual, processedEvents: undefined }, { ...expected, processedEvents: undefined });
    return actual;
  };
  const initial = await compare("current");
  await log.append({ type: "protocol_feedback", requestId: "current", text: "old feedback" });
  await log.append({ type: "context_input_snapshot", requestId: "current", messages: [{ role: "user", content: "date", timestamp: 0 }] });
  const recoveredBefore = recoveries;
  const incremental = await compare("current");
  assert.equal(recoveries, recoveredBefore, "unchanged archived tool result is not reloaded");
  assert.ok(incremental.processedEvents! < initial.processedEvents! / 10);
  cache = createReplayCache(dir, "c/model/prompt");
  assert.ok((await compare("current")).processedEvents! < 10);
  assert.equal(recoveries, recoveredBefore, "restart reuses verified projected tool content");
  const nextMessage = assistantText("", model); nextMessage.content = [{ type: "toolCall", id: "new-call", name: "read", arguments: { path: "file" } }];
  await log.append({ type: "model_message", requestId: "current", message: nextMessage });
  await log.append({ type: "tool_dispatch", requestId: "current", toolCallId: "new-call", toolName: "read", args: { path: "file" } });
  await log.append({ type: "tool_result", requestId: "current", toolCallId: "new-call", toolName: "read", result, archive });
  await compare("current");
  assert.equal(recoveries, recoveredBefore, "same verified archive reused by a new step");
  await log.append({ type: "answer_generated", requestId: "r2", text: "late" });
  await log.append({ type: "run_succeeded", runId: "r2", requestId: "r2", result: { kind: "model" } });
  await compare("current");
  await log.append({ type: "message", role: "user", requestId: "new-question", text: "next question" });
  await compare("new-question");
  const different = createReplayCache(dir, "c/model/changed-prompt");
  assert.equal((await different.replay(log, "current", model, false)).processedEvents, (await log.read()).length);
  await log.append({ type: "memory_excluded", nodeId: "r4" });
  assert.equal((await compare("current")).processedEvents, (await replayEvents(log, "current", model)).events.length);
  await log.append({ type: "conversation_reset" });
  await log.append({ type: "message", role: "user", requestId: "next", text: "new" });
  await compare("next");
  const root = join(dir, "context-projections");
  for (const name of await readdir(root)) await writeFile(join(root, name), "broken");
  cache = createReplayCache(dir, "c/model/prompt"); await compare("next");
});
